apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: loginapp
spec:
  selector:
    app: postgres-db
  ports:
  - port: 80
    targetPort: 5432
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: loginapp
spec:
  selector:
    matchLabels:
      app: postgres-db
  serviceName: postgres-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      volumes:
      - name: postgres-volume
        emptyDir: {}

      containers:
      - name: postgres-db
        image: postgres:13
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: loginapp
        volumeMounts:
        - name: postgres-volume
          mountPath: /var/lib/postgresql/data