version: '3.9'
services:
  app:
    image: monyorojoseph/loginapp
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "setup.wsgi"]
    networks:
      - loginapp
      - monitoring
    ports:
      - 8000:8000
    environment:
      # - ALLOWED_HOSTS=localhost prometheus
      - DEBUG=False
      - SECRET_KEY=ca13f095ca2e07882b9db2b1f980328c9f8669e9b5d65b51ccd15cfe4e03018d
      - DB_URL=postgres://postgres:postgres@db:5432/loginapp
    depends_on:
      - db
      
  db:
    image: postgres:13
    networks:
      - loginapp
    ports:
      - 5432:5432
    volumes:
      - db_vm:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: loginapp
 
networks:
  loginapp:
    name: loginapp
    attachable: true
  monitoring:
    name: monitoring
    external: true

volumes:
  db_vm: