version: '3.9'
services:
  app:
    image: monyorojoseph/loginapp
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "setup.wsgi"]
    networks:
      - loginapp
      - monitoring
    ports:
      - 8000:8000
    environment:
      # - ALLOWED_HOSTS=localhost prometheus
      - DEBUG=False
      - SECRET_KEY=ca13f095ca2e07882b9db2b1f980328c9f8669e9b5d65b51ccd15cfe4e03018d
      - DB_URL=postgres://postgres:postgres@db:5432/loginapp
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_HOST_USER=xxxx@gmail.com
      - EMAIL_HOST_PASSWORD=yyyyy
      - REDIS_URL=redis://redis:6379/?db=1
    depends_on:
      - db

  task:
    image: monyorojoseph/loginapp
    command: ["manage.py", "run_heuy"]
    networks:
      - loginapp
      # - monitoring
    environment:
      # - ALLOWED_HOSTS=localhost prometheus
      - DEBUG=False
      - SECRET_KEY=ca13f095ca2e07882b9db2b1f980328c9f8669e9b5d65b51ccd15cfe4e03018d
      - DB_URL=postgres://postgres:postgres@db:5432/loginapp
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_HOST_USER=xxxx@gmail.com
      - EMAIL_HOST_PASSWORD=yyyyy
      - REDIS_URL=redis://redis:6379/?db=1
    depends_on:
      - db
      - redis
      
  db:
    image: postgres:13
    networks:
      - loginapp
    ports:
      - 5432:5432
    volumes:
      - db_vm:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: loginapp


  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_vm:/usr/local/etc/redis
    networks:
      - loginapp
 
networks:
  loginapp:
    name: loginapp
    attachable: true
  monitoring:
    name: monitoring
    external: true

volumes:
  db_vm:
  redis_vm: