apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp
  labels:
    app: loginapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginapp
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
      - name: app
        image: monyorojoseph/loginapp:v0.0.1
        command: ["gunicorn", "--bind", "0.0.0.0:8000", "setup.wsgi"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: ALLOWED_HOSTS
          value: loginapp-svc localhost 127.0.0.1
        - name: SECRET_KEY
          value: 7a46b437b5d9ddbe9799b298b0f1237474182c98f618f24475a35e7be4a03812
        - name: DB_URL
          value: postgres://postgres:postgres@postgres-db:5432/loginapp

        # livenessProbe:
        #   initialDelaySeconds: 10
        #   periodSeconds: 15
        #   failureThreshold: 1
        #   httpGet:
        #     path: /
        #     port: 8000

        # readinessProbe:
        #   tcpSocket:
        #     port: 8000
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          failureThreshold: 1
          periodSeconds: 10

          
