name: Build App Image

on:
    push: 
        branches: [ master ]
    workflow_dispatch:


env:
    ALLOWED_HOSTS: localhost
    SECRET_KEY: insecure-secret-key
    DB_URL: postgres://postgres:postgres@localhost:5432/loginapp


jobs:
    test:
        runs-on: ubuntu-latest
        services:
            db:
                image: postgres:13
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                    POSTGRES_DB: loginapp
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            
        
        steps:

            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            - name: Run Migrations and Tests
              run: |
                    python manage.py migrate
                    python manage.py test

            - name: Run Server and Quit
              run: python manage.py runserver &

    build:
      runs-on: ubuntu-latest
      needs: test
      steps:
          - name: Build Checkout
            uses: actions/checkout@v4

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Build Image and Push
            run: |
                  docker build -t monyorojoseph/loginapp -f docker/Django/Dockerfile .
                  docker push monyorojoseph/loginapp