name: Monitoring Build

on:
    push: 
        paths: 
            - docker/Grafana/**
            - docker/Prometheus/**
    workflow_dispatch:

jobs:
    build-prometheus:
        runs-on: ubuntu-latest
        steps:
            - name: Build Checkout
              uses: actions/checkout@v4
  
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
  
            - name: Build Image and Push
              run: |
                    docker build -t monyorojoseph/prometheus -f docker/Prometheus/Dockerfile ./docker/Prometheus/
                    docker push monyorojoseph/prometheus

    build-grafana:
        runs-on: ubuntu-latest
        steps:
            - name: Build Checkout
              uses: actions/checkout@v4
  
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
  
            - name: Build Image and Push
              run: |
                    docker build -t monyorojoseph/grafana -f docker/Grafana/Dockerfile ./docker/Grafana/
                    docker push monyorojoseph/grafana
